### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by mcsimenc** [gaborvecsei/Color-Tracker#16]
Hi, this looks interesting.  I installed using pip  running Python 3.6.1 but see this error.

```
>>> import color_tracker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "color_tracker.py", line 6, in <module>
    cam = color_tracker.WebCamera(video_src=0)
AttributeError: module 'color_tracker' has no attribute 'WebCamera'
```

**Comment by gaborvecsei** [comment]
Is this issue still in your scope?

**Comment by mcsimenc** [comment]
It's not. I'll close it.
